export const ADD_QUENTITY_OF_PRODUCT = "ADD_QUENTITY_OF_PRODUCT";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_TO_CART = "REMOVE_TO_CART";
export const FETCH_WISHLIST_DATA = "FETCH_WISHLIST_DATA";
export const ADD_WISHLIST_DATA = "ADD_WISHLIST_DATA";
export const REMOVE_QUENTITY_OF_PRODUCT = "REMOVE_QUENTITY_OF_PRODUCT";
export const PRODUCT_NAME = "PRODUCT_NAME";
